name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Build frontend with nix
        - uses: actions/checkout@v2.4.0
        - uses: cachix/install-nix-action@v15
          with:
            nix_path: nixpkgs=channel:nixos-unstable
        - run: nix-build -A ghcjs.frontend -o result
      - name: Archive frontend result
        - uses: actions/upload-artifact@v2
        - with:
          - name: ghcjs-frontend
          - path: result
